## code to prepare `job_survey` dataset goes here

# the data in job_survey was randomly generated from a Qualtrics survey file
# then copied as a tribble with the {datapasta} r package
job_survey <- 
  tibble::tribble(
    ~survey_name,  ~Q1,           ~Q2,                   ~Q3,                                  ~Q4,  ~Q5,
           "job", 100L,      "Austin",          "Consulting",              "Somewhat dissatisfied", 163L,
           "job",  81L, "San Antonio",          "Consulting", "Neither satisfied nor dissatisfied",  48L,
           "job",  51L,      "Austin",          "Consulting",                "Extremely satisfied", 190L,
           "job",  81L,      "Austin",          "Technology",             "Extremely dissatisfied",  25L,
           "job",  80L,      "Dallas",          "Consulting",                "Extremely satisfied", 143L,
           "job",  32L,  "Fort Worth",              "Energy",                 "Somewhat satisfied", 233L,
           "job",  65L,      "Dallas",          "Consulting",              "Somewhat dissatisfied",  43L,
           "job",  57L,     "Houston",          "Healthcare",              "Somewhat dissatisfied", 243L,
           "job",  43L,      "Dallas", "Government Services", "Neither satisfied nor dissatisfied", 158L,
           "job",  94L,  "Fort Worth",          "Healthcare",             "Extremely dissatisfied", 235L,
           "job",  25L,  "Fort Worth",              "Energy",              "Somewhat dissatisfied", 245L,
           "job",  83L, "San Antonio",              "Energy",                 "Somewhat satisfied", 195L,
           "job",  61L,     "Houston",          "Technology",                "Extremely satisfied", 248L,
           "job",  66L,      "Austin",          "Technology",             "Extremely dissatisfied", 170L,
           "job",  85L, "San Antonio",          "Healthcare",              "Somewhat dissatisfied",  60L,
           "job",  27L,      "Dallas",          "Technology", "Neither satisfied nor dissatisfied",  30L,
           "job",  25L,      "Dallas",              "Energy",             "Extremely dissatisfied", 190L,
           "job",  38L,  "Fort Worth",          "Consulting",              "Somewhat dissatisfied", 195L,
           "job",  21L,     "Houston",          "Healthcare",             "Extremely dissatisfied", 245L,
           "job",  76L,      "Dallas",          "Technology",                "Extremely satisfied", 155L,
           "job",  29L,     "Houston",          "Healthcare", "Neither satisfied nor dissatisfied",  55L,
           "job",  94L,      "Dallas",          "Consulting", "Neither satisfied nor dissatisfied",  90L,
           "job",  38L,  "Fort Worth",              "Energy",              "Somewhat dissatisfied", 240L,
           "job",  52L,      "Dallas",          "Consulting",              "Somewhat dissatisfied", 133L,
           "job",  94L, "San Antonio",          "Technology",              "Somewhat dissatisfied", 238L,
           "job",  77L,      "Dallas",              "Energy",              "Somewhat dissatisfied", 140L,
           "job",  48L,  "Fort Worth",          "Consulting",                 "Somewhat satisfied", 218L,
           "job",  86L,     "Houston",          "Consulting",                 "Somewhat satisfied", 175L,
           "job",  58L, "San Antonio",          "Healthcare",                 "Somewhat satisfied", 163L,
           "job",  61L,      "Dallas",          "Healthcare",              "Somewhat dissatisfied",  98L,
           "job",  25L, "San Antonio",          "Consulting",                "Extremely satisfied",  53L,
           "job",  90L,  "Fort Worth",              "Energy",             "Extremely dissatisfied", 135L,
           "job",  90L,      "Austin",              "Energy",                 "Somewhat satisfied",  30L,
           "job",  83L,      "Dallas",          "Consulting",             "Extremely dissatisfied", 213L,
           "job",  26L,  "Fort Worth",              "Energy",                 "Somewhat satisfied", 140L,
           "job",  88L,      "Austin",          "Healthcare",             "Extremely dissatisfied",  55L,
           "job",  75L,      "Austin",          "Consulting",              "Somewhat dissatisfied", 233L,
           "job",  48L,      "Dallas",          "Healthcare",                 "Somewhat satisfied", 238L,
           "job",  87L, "San Antonio",          "Consulting",             "Extremely dissatisfied",  55L,
           "job",  39L,      "Dallas",          "Technology", "Neither satisfied nor dissatisfied",  90L,
           "job",  39L,      "Dallas",          "Technology",             "Extremely dissatisfied", 143L,
           "job",  25L,      "Austin",          "Consulting",                 "Somewhat satisfied",  83L,
           "job",  48L,  "Fort Worth",          "Healthcare",                 "Somewhat satisfied",  28L,
           "job",  21L,      "Dallas",              "Energy", "Neither satisfied nor dissatisfied", 180L,
           "job",  29L,      "Austin",          "Consulting",                "Extremely satisfied", 165L,
           "job",  21L,      "Dallas", "Government Services",              "Somewhat dissatisfied", 143L,
           "job",  65L,     "Houston",          "Technology",             "Extremely dissatisfied",  58L,
           "job",  77L,     "Houston",          "Healthcare",              "Somewhat dissatisfied", 160L,
           "job",  21L, "San Antonio",          "Consulting",                "Extremely satisfied", 248L,
           "job",  18L,      "Dallas",          "Healthcare",                "Extremely satisfied",  55L,
           "job",  46L,     "Houston",          "Technology",             "Extremely dissatisfied", 130L,
           "job",  69L, "San Antonio",          "Consulting",             "Extremely dissatisfied", 178L,
           "job",  83L,      "Austin",          "Healthcare",             "Extremely dissatisfied", 250L,
           "job",  71L,      "Dallas",              "Energy",                 "Somewhat satisfied", 220L,
           "job",  94L,      "Dallas", "Government Services", "Neither satisfied nor dissatisfied", 225L,
           "job",  45L,      "Dallas", "Government Services",                "Extremely satisfied", 170L,
           "job",  89L, "San Antonio",              "Energy",                 "Somewhat satisfied", 203L,
           "job",  38L,      "Dallas",              "Energy",                "Extremely satisfied", 223L,
           "job",  23L,      "Dallas",          "Consulting", "Neither satisfied nor dissatisfied", 115L,
           "job",  48L,  "Fort Worth", "Government Services",                "Extremely satisfied", 190L,
           "job",  90L,     "Houston", "Government Services", "Neither satisfied nor dissatisfied", 250L,
           "job",  93L,      "Austin",          "Consulting",                "Extremely satisfied",  70L,
           "job",  98L,  "Fort Worth",          "Healthcare",              "Somewhat dissatisfied", 208L,
           "job",  87L, "San Antonio",              "Energy",              "Somewhat dissatisfied",  28L,
           "job",  21L,  "Fort Worth", "Government Services",             "Extremely dissatisfied",  65L,
           "job",  48L,     "Houston", "Government Services",                 "Somewhat satisfied",  20L,
           "job",  99L,      "Dallas", "Government Services",             "Extremely dissatisfied", 130L,
           "job",  43L,  "Fort Worth",          "Technology",              "Somewhat dissatisfied", 248L,
           "job",  66L,     "Houston",          "Technology",              "Somewhat dissatisfied",  78L,
           "job",  63L,      "Austin",          "Technology",                 "Somewhat satisfied", 158L,
           "job",  23L,  "Fort Worth",              "Energy",              "Somewhat dissatisfied", 153L,
           "job",  31L,  "Fort Worth",          "Consulting", "Neither satisfied nor dissatisfied",  20L,
           "job",  49L,      "Austin",          "Consulting",             "Extremely dissatisfied", 115L,
           "job",  61L,  "Fort Worth",          "Consulting",                "Extremely satisfied", 188L,
           "job",  60L,  "Fort Worth",              "Energy",                 "Somewhat satisfied",  98L,
           "job",  61L,      "Dallas",          "Consulting",             "Extremely dissatisfied", 225L,
           "job",  47L,     "Houston",          "Healthcare",             "Extremely dissatisfied", 203L,
           "job",  52L,      "Austin", "Government Services",             "Extremely dissatisfied",  73L,
           "job",  88L,  "Fort Worth",          "Technology", "Neither satisfied nor dissatisfied",  55L,
           "job",  52L,     "Houston", "Government Services",                 "Somewhat satisfied", 180L,
           "job",  88L,     "Houston", "Government Services",                 "Somewhat satisfied", 228L,
           "job",  40L,      "Dallas",              "Energy",              "Somewhat dissatisfied", 145L,
           "job",  37L,      "Dallas", "Government Services",                "Extremely satisfied",   0L,
           "job",  66L,  "Fort Worth",              "Energy",              "Somewhat dissatisfied",  73L,
           "job",  29L,  "Fort Worth", "Government Services",              "Somewhat dissatisfied",   0L,
           "job",  65L,      "Dallas",          "Technology", "Neither satisfied nor dissatisfied", 100L,
           "job",  97L,     "Houston",          "Consulting",                "Extremely satisfied", 138L,
           "job",  53L,  "Fort Worth",              "Energy",              "Somewhat dissatisfied", 165L,
           "job",  94L,     "Houston",          "Technology",                 "Somewhat satisfied", 123L,
           "job",  61L, "San Antonio",          "Consulting",                 "Somewhat satisfied",  13L,
           "job",  50L,      "Dallas",          "Consulting",              "Somewhat dissatisfied",  48L,
           "job",  37L,      "Austin",          "Consulting",                 "Somewhat satisfied",  13L,
           "job",  80L,      "Austin",              "Energy",             "Extremely dissatisfied",  98L,
           "job",  67L,     "Houston", "Government Services",                "Extremely satisfied", 218L,
           "job",  71L,      "Austin",          "Healthcare",              "Somewhat dissatisfied",  48L,
           "job",  82L,     "Houston",          "Technology",                "Extremely satisfied", 148L,
           "job",  59L,      "Austin",          "Consulting",              "Somewhat dissatisfied", 178L,
           "job",  25L,      "Austin",          "Consulting",                 "Somewhat satisfied",  60L,
           "job",  89L,      "Austin",          "Healthcare",                "Extremely satisfied", 235L,
           "job",  21L,     "Houston",              "Energy",              "Somewhat dissatisfied",  95L,
           "job",  70L,  "Fort Worth",          "Consulting",             "Extremely dissatisfied", 198L,
           "job",  80L, "San Antonio",              "Energy",              "Somewhat dissatisfied", 200L,
           "job",  69L,  "Fort Worth",          "Technology", "Neither satisfied nor dissatisfied",  63L,
           "job",  80L,  "Fort Worth",          "Consulting",             "Extremely dissatisfied",  10L,
           "job",  83L,      "Dallas",          "Technology",                "Extremely satisfied",  20L,
           "job",  52L,     "Houston",              "Energy",                "Extremely satisfied", 145L,
           "job",  78L,      "Austin",          "Technology",              "Somewhat dissatisfied", 173L,
           "job",  71L,      "Dallas", "Government Services",                 "Somewhat satisfied", 210L,
           "job",  19L,     "Houston",          "Technology",             "Extremely dissatisfied",  65L,
           "job",  84L,     "Houston",          "Technology",              "Somewhat dissatisfied",  33L,
           "job",  22L,      "Austin",          "Consulting",              "Somewhat dissatisfied", 213L,
           "job",  35L,      "Austin",          "Technology",                "Extremely satisfied",  90L,
           "job",  61L,  "Fort Worth",          "Consulting",              "Somewhat dissatisfied",  28L,
           "job",  29L,      "Austin",          "Consulting",              "Somewhat dissatisfied", 118L,
           "job",  60L,      "Austin",              "Energy",             "Extremely dissatisfied",  73L,
           "job",  37L,      "Austin",          "Consulting",             "Extremely dissatisfied", 220L,
           "job",  46L,      "Dallas",              "Energy",                "Extremely satisfied",  15L,
           "job",  39L, "San Antonio",          "Healthcare",             "Extremely dissatisfied", 135L,
           "job",  48L,     "Houston",          "Healthcare",             "Extremely dissatisfied", 118L,
           "job",  29L,      "Dallas",          "Consulting",                 "Somewhat satisfied", 143L,
           "job",  44L,  "Fort Worth",          "Consulting", "Neither satisfied nor dissatisfied",  68L,
           "job",  71L,     "Houston",          "Technology",             "Extremely dissatisfied",   8L,
           "job",  66L,      "Austin",          "Healthcare", "Neither satisfied nor dissatisfied", 248L,
           "job",  76L,      "Austin",          "Consulting",                "Extremely satisfied", 145L,
           "job",  25L,      "Dallas",          "Technology",             "Extremely dissatisfied",  60L,
           "job",  75L,     "Houston",          "Healthcare",             "Extremely dissatisfied", 120L,
           "job",  89L,  "Fort Worth", "Government Services", "Neither satisfied nor dissatisfied", 105L,
           "job",  98L,      "Austin",          "Healthcare",              "Somewhat dissatisfied", 128L,
           "job",  29L,      "Austin",          "Technology",             "Extremely dissatisfied", 128L,
           "job",  66L, "San Antonio",          "Healthcare",              "Somewhat dissatisfied",   0L,
           "job",  79L, "San Antonio",          "Consulting",                "Extremely satisfied", 115L,
           "job",  51L, "San Antonio",          "Technology",             "Extremely dissatisfied",  20L,
           "job",  34L,      "Dallas", "Government Services",                "Extremely satisfied", 123L,
           "job",  82L, "San Antonio",          "Consulting",             "Extremely dissatisfied",  20L,
           "job",  37L, "San Antonio",          "Healthcare",                "Extremely satisfied",  73L,
           "job",  92L,      "Austin",              "Energy",              "Somewhat dissatisfied", 138L,
           "job",  70L, "San Antonio",              "Energy",              "Somewhat dissatisfied", 220L,
           "job",  35L,  "Fort Worth", "Government Services",              "Somewhat dissatisfied",  28L,
           "job",  94L,      "Dallas",          "Consulting", "Neither satisfied nor dissatisfied",  90L,
           "job",  98L, "San Antonio", "Government Services",             "Extremely dissatisfied", 230L,
           "job",  52L,      "Austin",          "Healthcare", "Neither satisfied nor dissatisfied", 143L,
           "job",  36L,      "Dallas",          "Consulting",                 "Somewhat satisfied", 145L,
           "job",  78L,      "Dallas", "Government Services",                "Extremely satisfied",  88L,
           "job",  51L,  "Fort Worth",          "Consulting", "Neither satisfied nor dissatisfied", 228L,
           "job",  40L,     "Houston",          "Technology",             "Extremely dissatisfied", 118L,
           "job",  79L,  "Fort Worth",              "Energy",              "Somewhat dissatisfied",  35L,
           "job",  75L,  "Fort Worth",          "Technology",                 "Somewhat satisfied",  70L,
           "job",  60L,     "Houston",          "Consulting",             "Extremely dissatisfied",  30L,
           "job",  86L,     "Houston",              "Energy",                 "Somewhat satisfied", 248L,
           "job",  49L, "San Antonio",              "Energy",             "Extremely dissatisfied", 205L,
           "job",  74L,      "Dallas", "Government Services",             "Extremely dissatisfied", 210L,
           "job",  86L, "San Antonio",          "Consulting",              "Somewhat dissatisfied", 168L,
           "job",  43L, "San Antonio",          "Consulting", "Neither satisfied nor dissatisfied",  90L,
           "job",  20L, "San Antonio",          "Healthcare", "Neither satisfied nor dissatisfied", 190L,
           "job",  21L,     "Houston",          "Healthcare",              "Somewhat dissatisfied", 160L,
           "job",  20L,  "Fort Worth",              "Energy",                "Extremely satisfied", 215L,
           "job",  52L,      "Austin",              "Energy",                 "Somewhat satisfied", 150L,
           "job",  43L,  "Fort Worth",          "Technology",              "Somewhat dissatisfied", 233L,
           "job",  92L,     "Houston", "Government Services",                 "Somewhat satisfied", 155L,
           "job",  68L, "San Antonio", "Government Services",                "Extremely satisfied", 118L,
           "job",  67L,     "Houston",          "Healthcare",             "Extremely dissatisfied",  25L,
           "job",  97L,  "Fort Worth", "Government Services", "Neither satisfied nor dissatisfied", 183L,
           "job",  65L, "San Antonio", "Government Services",                 "Somewhat satisfied",  50L,
           "job",  45L,     "Houston",          "Consulting",             "Extremely dissatisfied",  10L,
           "job",  89L, "San Antonio",              "Energy", "Neither satisfied nor dissatisfied",  30L,
           "job",  55L,     "Houston",          "Technology", "Neither satisfied nor dissatisfied",  33L,
           "job",  84L, "San Antonio",          "Technology",              "Somewhat dissatisfied", 173L,
           "job",  99L, "San Antonio",          "Healthcare",                "Extremely satisfied",  75L,
           "job",  59L,      "Austin",          "Technology", "Neither satisfied nor dissatisfied",  48L,
           "job",  57L,      "Austin",              "Energy",             "Extremely dissatisfied",  85L,
           "job",  22L, "San Antonio",          "Healthcare",                 "Somewhat satisfied", 220L,
           "job",  25L,  "Fort Worth",          "Consulting", "Neither satisfied nor dissatisfied", 130L,
           "job",  48L,      "Dallas",              "Energy",                 "Somewhat satisfied", 143L,
           "job",  62L,      "Dallas",          "Healthcare", "Neither satisfied nor dissatisfied",  50L,
           "job",  80L, "San Antonio",          "Technology",             "Extremely dissatisfied", 170L,
           "job",  30L,      "Austin",          "Technology", "Neither satisfied nor dissatisfied",  23L,
           "job",  92L, "San Antonio",          "Healthcare",              "Somewhat dissatisfied", 228L,
           "job",  70L, "San Antonio",          "Technology",             "Extremely dissatisfied", 183L,
           "job",  57L,  "Fort Worth",          "Consulting",              "Somewhat dissatisfied", 248L,
           "job",  70L,  "Fort Worth", "Government Services",              "Somewhat dissatisfied", 228L,
           "job",  70L, "San Antonio", "Government Services",             "Extremely dissatisfied",   8L,
           "job",  82L,      "Dallas",          "Healthcare",              "Somewhat dissatisfied", 188L,
           "job",  43L,      "Austin", "Government Services",                "Extremely satisfied", 153L,
           "job",  95L,     "Houston", "Government Services",              "Somewhat dissatisfied", 248L,
           "job",  54L,      "Dallas",              "Energy",                 "Somewhat satisfied", 108L,
           "job",  66L,  "Fort Worth",          "Technology",             "Extremely dissatisfied", 233L,
           "job",  85L,      "Austin",          "Technology",                "Extremely satisfied", 160L,
           "job",  85L,      "Dallas",          "Technology",                "Extremely satisfied",  15L,
           "job",  42L,      "Austin",          "Technology",                 "Somewhat satisfied",  20L,
           "job",  41L,     "Houston", "Government Services",             "Extremely dissatisfied", 125L,
           "job",  96L,      "Austin",          "Technology",              "Somewhat dissatisfied",  10L,
           "job",  51L,  "Fort Worth",          "Consulting",                 "Somewhat satisfied",  40L,
           "job",  98L,      "Austin", "Government Services",                "Extremely satisfied", 195L,
           "job",  98L, "San Antonio",              "Energy", "Neither satisfied nor dissatisfied",  38L,
           "job",  75L,  "Fort Worth", "Government Services",              "Somewhat dissatisfied",  43L,
           "job",  93L,     "Houston",          "Healthcare", "Neither satisfied nor dissatisfied", 155L,
           "job",  61L,     "Houston",          "Technology",                "Extremely satisfied", 225L,
           "job",  27L,      "Dallas",          "Technology",                "Extremely satisfied",  28L,
           "job",  49L,      "Austin",          "Technology",              "Somewhat dissatisfied", 208L,
           "job",  43L,      "Dallas",          "Technology", "Neither satisfied nor dissatisfied", 210L,
           "job",  45L,  "Fort Worth", "Government Services",                "Extremely satisfied", 165L,
           "job",  33L,     "Houston", "Government Services",                "Extremely satisfied",  45L,
           "job",  96L,      "Austin", "Government Services",                 "Somewhat satisfied",  68L,
           "job",  19L,      "Dallas", "Government Services",             "Extremely dissatisfied", 233L,
           "job",  83L, "San Antonio",          "Consulting",                "Extremely satisfied", 125L,
           "job",  92L, "San Antonio",              "Energy",                "Extremely satisfied",  98L,
           "job",  78L,     "Houston", "Government Services",                 "Somewhat satisfied",  60L,
           "job",  85L,      "Austin",          "Technology",             "Extremely dissatisfied", 168L,
           "job",  33L,      "Austin",              "Energy",              "Somewhat dissatisfied", 240L,
           "job",  86L,      "Dallas", "Government Services",                 "Somewhat satisfied",  85L,
           "job",  43L,      "Dallas",              "Energy", "Neither satisfied nor dissatisfied", 215L,
           "job",  26L,     "Houston", "Government Services",                "Extremely satisfied", 243L,
           "job",  58L, "San Antonio",          "Consulting",              "Somewhat dissatisfied", 180L,
           "job",  34L,  "Fort Worth", "Government Services",                 "Somewhat satisfied", 243L,
           "job",  24L,      "Austin",          "Technology",              "Somewhat dissatisfied",   3L,
           "job",  98L,      "Dallas",          "Consulting", "Neither satisfied nor dissatisfied", 195L,
           "job",  64L,      "Austin", "Government Services",              "Somewhat dissatisfied", 123L,
           "job",  58L,  "Fort Worth", "Government Services",                 "Somewhat satisfied",  93L,
           "job",  44L,     "Houston", "Government Services",             "Extremely dissatisfied",  63L,
           "job",  52L,      "Dallas",          "Technology",              "Somewhat dissatisfied",  55L,
           "job",  70L,      "Austin",              "Energy",                 "Somewhat satisfied", 158L,
           "job",  52L, "San Antonio", "Government Services", "Neither satisfied nor dissatisfied", 175L,
           "job",  76L,     "Houston",          "Technology",              "Somewhat dissatisfied", 240L,
           "job",  91L,     "Houston",              "Energy",              "Somewhat dissatisfied", 153L,
           "job",  63L,      "Dallas",          "Consulting", "Neither satisfied nor dissatisfied", 138L,
           "job",  88L,      "Austin",          "Technology",                 "Somewhat satisfied", 205L,
           "job",  82L,      "Austin",          "Consulting",                "Extremely satisfied", 105L,
           "job",  50L, "San Antonio", "Government Services",             "Extremely dissatisfied", 125L,
           "job",  84L, "San Antonio",          "Healthcare",              "Somewhat dissatisfied",  20L,
           "job",  19L,      "Austin",          "Consulting", "Neither satisfied nor dissatisfied",  50L,
           "job",  80L, "San Antonio", "Government Services",              "Somewhat dissatisfied", 168L,
           "job",  52L,      "Austin", "Government Services",             "Extremely dissatisfied",  70L,
           "job",  18L, "San Antonio",          "Technology",                "Extremely satisfied", 170L,
           "job",  37L,      "Austin", "Government Services",                "Extremely satisfied", 250L,
           "job",  59L,      "Austin",          "Technology", "Neither satisfied nor dissatisfied", 148L,
           "job",  46L, "San Antonio",          "Technology",             "Extremely dissatisfied",  18L,
           "job",  65L,     "Houston", "Government Services",                "Extremely satisfied", 128L,
           "job",  52L,     "Houston",          "Consulting",                "Extremely satisfied",  78L,
           "job",  20L, "San Antonio",          "Technology",              "Somewhat dissatisfied", 125L,
           "job",  23L,      "Dallas", "Government Services",             "Extremely dissatisfied", 200L,
           "job",  31L,     "Houston", "Government Services", "Neither satisfied nor dissatisfied",  90L,
           "job",  84L,      "Austin",          "Technology",              "Somewhat dissatisfied",  98L,
           "job",  52L, "San Antonio",              "Energy",                 "Somewhat satisfied", 168L,
           "job",  88L,     "Houston",          "Technology",              "Somewhat dissatisfied", 208L,
           "job",  30L,  "Fort Worth",          "Consulting",              "Somewhat dissatisfied", 165L,
           "job",  98L,      "Dallas",              "Energy",                 "Somewhat satisfied",  75L,
           "job",  47L,     "Houston",          "Technology",                "Extremely satisfied", 220L,
           "job",  41L,  "Fort Worth",          "Healthcare",                 "Somewhat satisfied", 220L,
           "job",  37L,      "Dallas",              "Energy",              "Somewhat dissatisfied", 163L,
           "job",  24L,     "Houston", "Government Services",             "Extremely dissatisfied", 120L,
           "job",  62L, "San Antonio",          "Consulting",              "Somewhat dissatisfied", 168L,
           "job",  20L,     "Houston",          "Consulting",              "Somewhat dissatisfied", 215L,
           "job",  27L, "San Antonio",          "Technology", "Neither satisfied nor dissatisfied", 208L,
           "job",  41L, "San Antonio",              "Energy", "Neither satisfied nor dissatisfied", 143L,
           "job",  34L,      "Dallas",          "Technology",              "Somewhat dissatisfied", 235L,
           "job",  51L,      "Austin",              "Energy", "Neither satisfied nor dissatisfied",   3L,
           "job",  75L,      "Austin",          "Technology",             "Extremely dissatisfied",  38L,
           "job",  95L, "San Antonio", "Government Services",              "Somewhat dissatisfied", 250L,
           "job",  70L,  "Fort Worth",          "Technology", "Neither satisfied nor dissatisfied", 143L,
           "job",  65L, "San Antonio",              "Energy",              "Somewhat dissatisfied", 143L,
           "job",  19L,      "Austin",          "Healthcare", "Neither satisfied nor dissatisfied", 115L,
           "job",  25L,      "Dallas",              "Energy",                 "Somewhat satisfied", 118L,
           "job",  24L,  "Fort Worth",          "Technology",                 "Somewhat satisfied", 208L,
           "job",  32L,     "Houston",          "Consulting",                 "Somewhat satisfied", 133L,
           "job",  20L,     "Houston", "Government Services",                "Extremely satisfied", 145L,
           "job",  92L,     "Houston",          "Healthcare",              "Somewhat dissatisfied", 108L,
           "job",  52L,     "Houston",          "Technology",                 "Somewhat satisfied", 180L,
           "job",  70L,     "Houston",          "Technology", "Neither satisfied nor dissatisfied", 238L,
           "job",  98L, "San Antonio",              "Energy",                "Extremely satisfied", 128L,
           "job",  75L,      "Dallas",              "Energy", "Neither satisfied nor dissatisfied",  10L,
           "job",  25L, "San Antonio", "Government Services",                "Extremely satisfied",   3L,
           "job",  90L,     "Houston",          "Healthcare",                 "Somewhat satisfied",  85L,
           "job",  64L,  "Fort Worth", "Government Services",             "Extremely dissatisfied", 195L,
           "job",  47L,      "Austin",              "Energy",             "Extremely dissatisfied", 248L,
           "job",  86L,  "Fort Worth", "Government Services",             "Extremely dissatisfied",  48L,
           "job",  89L, "San Antonio",          "Technology", "Neither satisfied nor dissatisfied",  98L,
           "job",  43L,      "Austin",          "Technology",                "Extremely satisfied", 123L,
           "job",  75L,     "Houston", "Government Services", "Neither satisfied nor dissatisfied", 185L,
           "job",  53L, "San Antonio",          "Consulting",                "Extremely satisfied", 228L,
           "job",  93L, "San Antonio", "Government Services", "Neither satisfied nor dissatisfied", 205L,
           "job",  73L, "San Antonio",          "Consulting",             "Extremely dissatisfied", 233L,
           "job",  84L,     "Houston",              "Energy",                "Extremely satisfied", 153L,
           "job",  46L,  "Fort Worth",          "Consulting", "Neither satisfied nor dissatisfied", 123L,
           "job",  71L,      "Austin", "Government Services",                 "Somewhat satisfied",  95L,
           "job",  29L,      "Austin",          "Healthcare",             "Extremely dissatisfied",   3L,
           "job",  83L,     "Houston",          "Healthcare",             "Extremely dissatisfied",   8L,
           "job",  26L,     "Houston",          "Technology",              "Somewhat dissatisfied", 143L,
           "job",  89L,      "Dallas",          "Healthcare",             "Extremely dissatisfied", 200L,
           "job",  45L,  "Fort Worth", "Government Services", "Neither satisfied nor dissatisfied",  90L,
           "job",  19L, "San Antonio",          "Healthcare",                 "Somewhat satisfied", 235L,
           "job",  56L, "San Antonio",          "Technology",              "Somewhat dissatisfied",  65L,
           "job",  87L,     "Houston",          "Healthcare",              "Somewhat dissatisfied", 138L,
           "job",  40L,     "Houston",          "Consulting",              "Somewhat dissatisfied",  68L,
           "job",  43L,      "Austin",          "Healthcare", "Neither satisfied nor dissatisfied", 175L,
           "job",  84L,     "Houston",              "Energy",                 "Somewhat satisfied", 115L,
           "job",  98L,      "Dallas",          "Technology",              "Somewhat dissatisfied",  80L,
           "job",  83L, "San Antonio",          "Consulting",                 "Somewhat satisfied", 208L,
           "job",  44L,      "Austin", "Government Services",              "Somewhat dissatisfied", 145L,
           "job",  41L,  "Fort Worth",          "Technology",              "Somewhat dissatisfied", 153L,
           "job",  82L, "San Antonio",          "Healthcare", "Neither satisfied nor dissatisfied", 210L,
           "job",  48L,     "Houston",          "Technology",                 "Somewhat satisfied",  38L,
           "job",  71L,      "Austin",              "Energy",                "Extremely satisfied",  30L,
           "job",  24L, "San Antonio", "Government Services",             "Extremely dissatisfied",  20L,
           "job",  98L, "San Antonio",          "Consulting",              "Somewhat dissatisfied", 245L,
           "job",  67L, "San Antonio",          "Consulting",              "Somewhat dissatisfied",  23L,
           "job",  82L,  "Fort Worth",          "Consulting",                "Extremely satisfied", 125L,
           "job",  23L,     "Houston", "Government Services",                 "Somewhat satisfied", 210L,
           "job",  63L,      "Dallas",              "Energy",                 "Somewhat satisfied",  25L,
           "job",  65L,      "Dallas", "Government Services",              "Somewhat dissatisfied",  58L,
           "job",  57L, "San Antonio", "Government Services",             "Extremely dissatisfied",  15L,
           "job",  79L,     "Houston",          "Technology",                "Extremely satisfied",  43L,
           "job",  82L,      "Dallas",          "Technology", "Neither satisfied nor dissatisfied", 120L,
           "job",  52L,     "Houston",          "Technology",             "Extremely dissatisfied", 125L,
           "job",  20L, "San Antonio",          "Healthcare", "Neither satisfied nor dissatisfied", 220L,
           "job",  24L,      "Austin",          "Technology",              "Somewhat dissatisfied", 163L,
           "job",  92L,      "Austin",              "Energy", "Neither satisfied nor dissatisfied",  50L,
           "job",  26L,      "Austin",          "Consulting",             "Extremely dissatisfied",  83L,
           "job",  36L,     "Houston",          "Consulting",                 "Somewhat satisfied", 145L,
           "job",  81L, "San Antonio", "Government Services",              "Somewhat dissatisfied",   8L,
           "job",  42L, "San Antonio",          "Healthcare", "Neither satisfied nor dissatisfied", 108L,
           "job",  75L,     "Houston",          "Consulting",                 "Somewhat satisfied", 138L,
           "job",  67L,      "Dallas",              "Energy",                 "Somewhat satisfied",  93L,
           "job",  95L,      "Austin",              "Energy",              "Somewhat dissatisfied",  53L,
           "job",  91L,      "Dallas",          "Consulting",              "Somewhat dissatisfied",  38L,
           "job",  75L,  "Fort Worth",          "Technology", "Neither satisfied nor dissatisfied", 110L,
           "job",  88L,      "Austin",          "Technology",                 "Somewhat satisfied", 230L,
           "job",  68L,     "Houston", "Government Services",                "Extremely satisfied", 125L,
           "job",  86L,      "Dallas",          "Technology",              "Somewhat dissatisfied",  50L,
           "job",  34L,     "Houston",          "Technology",             "Extremely dissatisfied", 165L,
           "job",  54L, "San Antonio", "Government Services",                 "Somewhat satisfied",  68L,
           "job",  91L, "San Antonio",          "Consulting",              "Somewhat dissatisfied",  43L,
           "job",  35L,      "Dallas",          "Consulting",                 "Somewhat satisfied", 113L,
           "job",  78L,  "Fort Worth",          "Healthcare",                 "Somewhat satisfied", 220L,
           "job",  39L,      "Austin",              "Energy", "Neither satisfied nor dissatisfied", 125L,
           "job",  71L, "San Antonio", "Government Services",              "Somewhat dissatisfied", 155L,
           "job",  39L,     "Houston", "Government Services", "Neither satisfied nor dissatisfied", 168L,
           "job",  34L, "San Antonio",          "Technology",                "Extremely satisfied",   0L,
           "job",  49L,     "Houston",          "Consulting",                "Extremely satisfied", 248L,
           "job",  63L,      "Dallas", "Government Services",                 "Somewhat satisfied", 193L,
           "job",  60L,     "Houston",          "Consulting",              "Somewhat dissatisfied", 225L,
           "job",  57L,  "Fort Worth", "Government Services",             "Extremely dissatisfied",  20L,
           "job",  39L,      "Austin",              "Energy",                 "Somewhat satisfied",  30L,
           "job",  81L, "San Antonio",          "Consulting",             "Extremely dissatisfied",  43L,
           "job",  86L,      "Austin", "Government Services",              "Somewhat dissatisfied",  28L,
           "job",  89L,      "Dallas",          "Consulting",             "Extremely dissatisfied",  40L,
           "job",  20L,      "Austin",          "Healthcare", "Neither satisfied nor dissatisfied", 143L,
           "job",  45L,      "Dallas",              "Energy",                "Extremely satisfied",  18L,
           "job", 100L,      "Dallas",          "Healthcare", "Neither satisfied nor dissatisfied", 218L,
           "job",  25L,  "Fort Worth",          "Consulting", "Neither satisfied nor dissatisfied",  68L,
           "job",  97L,     "Houston",          "Healthcare",                "Extremely satisfied", 140L,
           "job",  93L,     "Houston",              "Energy",                 "Somewhat satisfied", 185L,
           "job",  59L,     "Houston",              "Energy",             "Extremely dissatisfied",  28L,
           "job",  32L,      "Austin",          "Healthcare",                 "Somewhat satisfied", 215L,
           "job",  80L,     "Houston",          "Technology",             "Extremely dissatisfied",   5L,
           "job",  91L,     "Houston",              "Energy",             "Extremely dissatisfied",  55L,
           "job",  70L,  "Fort Worth",          "Technology",             "Extremely dissatisfied", 140L,
           "job",  85L,      "Austin",          "Consulting",              "Somewhat dissatisfied", 178L,
           "job",  76L, "San Antonio", "Government Services",                "Extremely satisfied", 170L,
           "job",  94L,      "Dallas",          "Technology", "Neither satisfied nor dissatisfied", 120L,
           "job",  63L, "San Antonio",          "Technology", "Neither satisfied nor dissatisfied", 130L,
           "job",  39L,  "Fort Worth",          "Technology", "Neither satisfied nor dissatisfied",  40L,
           "job",  94L,      "Dallas",          "Technology",             "Extremely dissatisfied", 210L,
           "job",  83L,  "Fort Worth",          "Technology",             "Extremely dissatisfied", 233L,
           "job",  53L,  "Fort Worth", "Government Services", "Neither satisfied nor dissatisfied", 198L,
           "job",  48L,      "Austin", "Government Services",                "Extremely satisfied",  68L,
           "job",  35L, "San Antonio",          "Technology",                 "Somewhat satisfied",  60L,
           "job",  46L,      "Dallas",          "Healthcare",             "Extremely dissatisfied", 250L,
           "job",  89L,     "Houston",          "Healthcare", "Neither satisfied nor dissatisfied",  95L,
           "job",  68L, "San Antonio",          "Healthcare",              "Somewhat dissatisfied",  33L,
           "job",  43L,     "Houston",              "Energy",             "Extremely dissatisfied", 195L,
           "job",  62L,     "Houston",          "Consulting",                 "Somewhat satisfied",  68L,
           "job",  39L,      "Dallas",              "Energy",             "Extremely dissatisfied", 188L,
           "job",  52L,      "Austin",              "Energy",             "Extremely dissatisfied", 223L,
           "job",  25L,  "Fort Worth",          "Technology", "Neither satisfied nor dissatisfied",  88L,
           "job",  24L, "San Antonio",              "Energy",             "Extremely dissatisfied",  28L,
           "job",  66L, "San Antonio", "Government Services",                 "Somewhat satisfied", 205L,
           "job",  25L, "San Antonio", "Government Services",              "Somewhat dissatisfied",  30L,
           "job",  40L,     "Houston",          "Healthcare", "Neither satisfied nor dissatisfied", 153L,
           "job",  75L, "San Antonio",              "Energy",             "Extremely dissatisfied",  13L,
           "job",  28L,     "Houston",          "Healthcare",             "Extremely dissatisfied",  58L,
           "job",  37L,  "Fort Worth", "Government Services",              "Somewhat dissatisfied", 200L,
           "job",  32L,  "Fort Worth",          "Technology", "Neither satisfied nor dissatisfied", 183L,
           "job",  63L,  "Fort Worth",          "Technology",              "Somewhat dissatisfied",  48L,
           "job", 100L,      "Austin",          "Consulting",             "Extremely dissatisfied", 180L,
           "job",  70L,  "Fort Worth", "Government Services",             "Extremely dissatisfied", 225L,
           "job",  93L,      "Dallas", "Government Services",                 "Somewhat satisfied", 205L,
           "job",  79L,  "Fort Worth",          "Technology",                 "Somewhat satisfied", 205L,
           "job",  64L,     "Houston",              "Energy",              "Somewhat dissatisfied",  13L,
           "job",  55L,     "Houston", "Government Services",             "Extremely dissatisfied", 250L,
           "job",  22L,  "Fort Worth",          "Technology",                 "Somewhat satisfied",  18L,
           "job",  41L,  "Fort Worth",          "Healthcare", "Neither satisfied nor dissatisfied",  83L,
           "job",  34L,      "Dallas",          "Healthcare", "Neither satisfied nor dissatisfied", 210L,
           "job",  46L,      "Dallas",              "Energy", "Neither satisfied nor dissatisfied", 195L,
           "job",  70L,  "Fort Worth",          "Consulting",                "Extremely satisfied",  78L,
           "job",  25L,      "Austin",          "Technology",             "Extremely dissatisfied", 118L,
           "job",  39L,      "Austin",              "Energy", "Neither satisfied nor dissatisfied", 160L,
           "job",  41L,      "Dallas", "Government Services",                "Extremely satisfied", 165L,
           "job",  32L, "San Antonio",              "Energy",              "Somewhat dissatisfied", 123L,
           "job",  73L, "San Antonio",              "Energy", "Neither satisfied nor dissatisfied", 205L,
           "job",  55L,     "Houston",          "Technology",             "Extremely dissatisfied", 238L,
           "job",  87L,     "Houston", "Government Services",             "Extremely dissatisfied", 110L,
           "job",  70L, "San Antonio",          "Healthcare", "Neither satisfied nor dissatisfied",  35L,
           "job",  45L,     "Houston",          "Consulting",             "Extremely dissatisfied", 238L,
           "job",  80L,      "Austin", "Government Services",              "Somewhat dissatisfied",  55L,
           "job",  48L, "San Antonio",          "Technology",                 "Somewhat satisfied", 225L,
           "job",  20L,      "Dallas",              "Energy",             "Extremely dissatisfied",  70L,
           "job",  56L,      "Dallas",          "Consulting",                "Extremely satisfied", 170L,
           "job",  38L, "San Antonio",              "Energy",              "Somewhat dissatisfied", 245L,
           "job",  75L,     "Houston", "Government Services",              "Somewhat dissatisfied",  13L,
           "job",  61L,      "Dallas",              "Energy", "Neither satisfied nor dissatisfied",  95L,
           "job",  54L,  "Fort Worth",              "Energy",              "Somewhat dissatisfied",  63L,
           "job",  29L,     "Houston",          "Consulting",                "Extremely satisfied", 138L,
           "job",  96L, "San Antonio", "Government Services",                 "Somewhat satisfied",  25L,
           "job",  65L,      "Austin", "Government Services",                "Extremely satisfied",  58L,
           "job",  57L,     "Houston", "Government Services",                 "Somewhat satisfied",  25L,
           "job",  45L,     "Houston", "Government Services", "Neither satisfied nor dissatisfied", 230L,
           "job",  89L,  "Fort Worth",              "Energy",                "Extremely satisfied", 213L,
           "job",  38L,      "Austin",          "Consulting",              "Somewhat dissatisfied", 208L,
           "job",  75L,      "Austin",              "Energy",              "Somewhat dissatisfied",  25L,
           "job",  59L,      "Austin",          "Technology",                 "Somewhat satisfied", 205L,
           "job",  65L, "San Antonio",          "Consulting",                "Extremely satisfied",  88L,
           "job",  18L,  "Fort Worth",          "Consulting", "Neither satisfied nor dissatisfied",  98L,
           "job",  89L,      "Dallas",              "Energy",                 "Somewhat satisfied", 160L,
           "job",  45L,      "Austin", "Government Services",                "Extremely satisfied",  40L,
           "job",  63L,     "Houston",              "Energy",             "Extremely dissatisfied", 245L,
           "job",  48L,      "Dallas",          "Healthcare",                 "Somewhat satisfied", 105L,
           "job",  64L,      "Dallas",          "Consulting",                "Extremely satisfied", 130L,
           "job",  91L, "San Antonio",              "Energy", "Neither satisfied nor dissatisfied",  40L,
           "job",  94L, "San Antonio",          "Technology", "Neither satisfied nor dissatisfied", 145L,
           "job",  35L,     "Houston", "Government Services",             "Extremely dissatisfied", 110L,
           "job",  29L,  "Fort Worth",              "Energy",              "Somewhat dissatisfied", 218L,
           "job",  54L,     "Houston",              "Energy", "Neither satisfied nor dissatisfied",  70L,
           "job",  22L,      "Austin", "Government Services",                "Extremely satisfied",  38L,
           "job",  82L,     "Houston", "Government Services", "Neither satisfied nor dissatisfied",  65L,
           "job",  89L,      "Dallas",          "Healthcare",                "Extremely satisfied",  38L,
           "job",  31L,      "Dallas",              "Energy", "Neither satisfied nor dissatisfied",  65L,
           "job",  23L,  "Fort Worth",          "Healthcare",             "Extremely dissatisfied", 170L,
           "job",  83L,  "Fort Worth",          "Consulting",                 "Somewhat satisfied", 140L,
           "job",  51L, "San Antonio", "Government Services",             "Extremely dissatisfied",  40L,
           "job",  97L,      "Austin",          "Healthcare",                "Extremely satisfied",  38L,
           "job",  52L,  "Fort Worth",          "Healthcare",             "Extremely dissatisfied", 110L,
           "job",  78L,     "Houston",          "Healthcare",              "Somewhat dissatisfied", 148L,
           "job",  56L,     "Houston",          "Consulting",             "Extremely dissatisfied", 213L,
           "job",  66L,      "Dallas", "Government Services", "Neither satisfied nor dissatisfied", 128L,
           "job",  88L,      "Austin",          "Healthcare",              "Somewhat dissatisfied", 123L,
           "job",  65L,      "Dallas",          "Healthcare",              "Somewhat dissatisfied", 185L,
           "job",  39L,     "Houston",          "Technology",                "Extremely satisfied", 223L,
           "job",  87L,      "Dallas",              "Energy",             "Extremely dissatisfied", 110L,
           "job",  53L,      "Dallas",              "Energy",              "Somewhat dissatisfied",  75L,
           "job",  98L,  "Fort Worth",          "Technology",                "Extremely satisfied", 210L,
           "job",  43L,  "Fort Worth", "Government Services", "Neither satisfied nor dissatisfied",  33L,
           "job",  68L,      "Dallas",          "Healthcare",                 "Somewhat satisfied", 190L,
           "job",  57L,      "Dallas", "Government Services",             "Extremely dissatisfied", 223L,
           "job",  62L, "San Antonio",          "Technology",                 "Somewhat satisfied",  85L,
           "job",  85L, "San Antonio", "Government Services", "Neither satisfied nor dissatisfied", 223L,
           "job",  62L, "San Antonio",              "Energy",                 "Somewhat satisfied", 140L,
           "job",  72L,     "Houston",          "Healthcare", "Neither satisfied nor dissatisfied", 103L,
           "job",  60L, "San Antonio",              "Energy",              "Somewhat dissatisfied",  60L,
           "job",  29L,      "Austin",          "Consulting",                "Extremely satisfied",  53L,
           "job",  64L,     "Houston",          "Technology",                 "Somewhat satisfied",  60L,
           "job",  21L,  "Fort Worth",          "Consulting",             "Extremely dissatisfied",  25L,
           "job",  82L, "San Antonio",          "Consulting",              "Somewhat dissatisfied",  73L,
           "job",  54L, "San Antonio",          "Consulting",                 "Somewhat satisfied",  35L,
           "job",  21L,  "Fort Worth",          "Healthcare",                 "Somewhat satisfied", 238L,
           "job",  96L,      "Austin",          "Healthcare",                 "Somewhat satisfied",  60L,
           "job",  18L,      "Dallas",          "Consulting",                "Extremely satisfied",  98L,
           "job",  65L, "San Antonio",          "Healthcare", "Neither satisfied nor dissatisfied", 228L,
           "job",  51L, "San Antonio",              "Energy", "Neither satisfied nor dissatisfied", 248L,
           "job",  23L,  "Fort Worth",              "Energy",              "Somewhat dissatisfied", 208L,
           "job",  78L,      "Dallas",          "Consulting",              "Somewhat dissatisfied", 138L,
           "job",  61L,      "Austin", "Government Services",                 "Somewhat satisfied",  45L,
           "job",  39L,      "Dallas", "Government Services",                "Extremely satisfied",  80L,
           "job",  19L,     "Houston",          "Technology",              "Somewhat dissatisfied",  90L,
           "job",  48L,      "Austin", "Government Services",                 "Somewhat satisfied", 115L,
           "job",  85L,     "Houston",          "Technology",             "Extremely dissatisfied",  65L,
           "job",  28L,     "Houston", "Government Services", "Neither satisfied nor dissatisfied",  15L,
           "job",  23L, "San Antonio",          "Consulting",              "Somewhat dissatisfied",  60L,
           "job",  92L, "San Antonio", "Government Services", "Neither satisfied nor dissatisfied", 180L,
           "job",  48L,      "Austin",          "Consulting",                 "Somewhat satisfied", 180L,
           "job",  91L,     "Houston",              "Energy", "Neither satisfied nor dissatisfied", 130L,
           "job",  85L,      "Austin",          "Technology",              "Somewhat dissatisfied", 135L,
           "job",  31L,     "Houston",              "Energy",              "Somewhat dissatisfied", 100L,
           "job",  93L,      "Austin",          "Technology",                "Extremely satisfied", 148L,
           "job",  60L,  "Fort Worth",          "Technology", "Neither satisfied nor dissatisfied", 153L,
           "job",  56L,      "Austin",          "Consulting", "Neither satisfied nor dissatisfied",   8L,
           "job",  34L,      "Dallas", "Government Services",                 "Somewhat satisfied",  93L,
           "job",  40L, "San Antonio",              "Energy",                 "Somewhat satisfied", 170L,
           "job",  89L,      "Dallas", "Government Services",                "Extremely satisfied", 190L,
           "job",  84L,     "Houston",              "Energy",             "Extremely dissatisfied", 215L,
           "job",  67L,  "Fort Worth",              "Energy", "Neither satisfied nor dissatisfied",  20L,
           "job",  55L, "San Antonio",          "Consulting",                "Extremely satisfied", 128L,
           "job",  24L, "San Antonio", "Government Services",                 "Somewhat satisfied",  13L,
           "job",  20L,      "Austin",          "Consulting",                 "Somewhat satisfied", 128L,
           "job",  60L,     "Houston",          "Technology",                "Extremely satisfied",  70L,
           "job",  62L,     "Houston",          "Consulting",              "Somewhat dissatisfied",  78L,
           "job",  88L,      "Dallas", "Government Services", "Neither satisfied nor dissatisfied",  25L,
           "job",  29L, "San Antonio",              "Energy",                "Extremely satisfied",  73L,
           "job",  65L,     "Houston",          "Healthcare",              "Somewhat dissatisfied",  68L,
           "job",  75L,  "Fort Worth",          "Consulting",                "Extremely satisfied",  33L,
           "job",  29L,      "Dallas", "Government Services",                "Extremely satisfied",  70L
    )

readr::write_csv(job_survey, "data-raw/job_survey.csv")
usethis::use_data(job_survey, overwrite = TRUE)
